version: '3'

services:
  hackatonservice:
    container_name: hackatonservice
    build:
      context: ../
      dockerfile: docker/Dockerfile.hackaton
    env_file:
      - ../.env
    ports:
      - ${HACKATON_PORT}:${HACKATON_PORT}
    depends_on:
      - hackatonservice_db
      - scoringservice

  hackatonservice_db:
    image: mysql:8.0
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--init-connect='SET NAMES utf8mb4;'"]
    container_name: hackatonservice_db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${HACKATON_DATABASE_NAME}
      MYSQL_USER: ${HACKATON_DATABASE_USER}
      MYSQL_PASSWORD: ${HACKATON_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3370:3306
    volumes:
      - ../../var/hackatonservice/database:/var/lib/mysql

  scoringservice:
    container_name: scoringservice
    build:
      context: ../
      dockerfile: docker/Dockerfile.scoring
    env_file:
      - ../.env
    depends_on:
      - hackatonservice_db

  scoringservice_db:
    image: mysql:8.0
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--init-connect='SET NAMES utf8mb4;'" ]
    container_name: scoringservice_db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${SCORING_DATABASE_NAME}
      MYSQL_USER: ${SCORING_DATABASE_USER}
      MYSQL_PASSWORD: ${SCORING_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3371:3306
    volumes:
      - ../../var/scoringservice/database:/var/lib/mysql