# -------- modules --------
FROM golang:1.16 AS modules

COPY ./go.mod ./go.sum /
RUN go mod download

# -------- build binary --------
FROM golang:1.16 AS builder

RUN useradd -u 1001 appuser

COPY --from=modules /go/pkg /go/pkg
COPY . /build
WORKDIR /build

RUN GOARCH=amd64 GOOS=linux CGO_ENABLED=0 \
    go build -o ./bin/scoringserviceeventsender ./src/scoringservice/cmd/eventsender

RUN chmod +x ./bin/scoringserviceeventsender

# -------- build image --------
FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /etc/passwd /etc/passwd
USER appuser

COPY --from=builder /build/bin/scoringserviceeventsender /app/bin/scoringserviceeventsender

WORKDIR /app

CMD ["/app/bin/scoringserviceeventsender"]