version: '3'

services:
  hackathonwebservice:
    container_name: hackathonwebservice
    build:
      context: ../
      dockerfile: docker/Dockerfile.hackathonwebservice
    env_file:
      - ../.env
    ports:
      - ${HACKATHON_PORT}:${HACKATHON_PORT}
    depends_on:
      - hackathonservice_db
      - scoringwebservice

  hackathonservice_db:
    image: mysql:8.0
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--init-connect='SET NAMES utf8mb4;'"]
    container_name: hackathonservice_db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${HACKATHON_DATABASE_NAME}
      MYSQL_USER: ${HACKATHON_DATABASE_USER}
      MYSQL_PASSWORD: ${HACKATHON_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3370:3306
    volumes:
      - ../../var/hackathonservice/database:/var/lib/mysql

  scoringwebservice:
    container_name: scoringwebservice
    build:
      context: ../
      dockerfile: docker/Dockerfile.scoringwebservice
    env_file:
      - ../.env
    ports:
      - ${SCORING_PORT}:${SCORING_PORT}
    depends_on:
      - scoringservice_db

  scoringservice_db:
    image: mysql:8.0
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--init-connect='SET NAMES utf8mb4;'" ]
    container_name: scoringservice_db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${SCORING_DATABASE_NAME}
      MYSQL_USER: ${SCORING_DATABASE_USER}
      MYSQL_PASSWORD: ${SCORING_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3371:3306
    volumes:
      - ../../var/scoringservice/database:/var/lib/mysql